name: pr milestone
on:
  pull_request:
    types: [closed]
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: secret
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
