name: milestone summary
on:
  schedule:
    - cron: '0 3 * * 1' # every Monday at 3am

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: milestone summary
        uses: ./.github/actions/scheduled-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          since: P3D
